#!/bin/sh
arm64=0
[[ "$ARCH" == "aarch64" ]] && arm64=1

set -xe

apk add linux-rpi linux-rpi4 linux-firmware-brcm raspberrypi-bootloader
# apk add zram-init
# rc-update add zram-init boot

echo "modules=loop,squashfs,sd-mod,usb-storage root=LABEL=ROOT rw rootfstype=ext4 elevator=deadline fsck.repair=yes console=tty1 selinux=0 rootwait quiet audit=0" > /boot/cmdline.txt
#smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 usbhid.mousepoll=8 snd-bcm2835.enable_compat_alsa=1 snd_bcm2835.enable_headphones=1

cat <<EOF > /boot/config.txt
[pi3]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi3+]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi4]
enable_gic=1
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
# dtoverlay=vc4-fkms-v3d
# max_framebuffers=2
kernel=vmlinuz-rpi4
initramfs initramfs-rpi4
[all]
arm_64bit=$arm64
enable_uart=1
dtparam=audio=on
include usercfg.txt
EOF

cat <<EOF > /boot/usercfg.txt
dtparam=i2c=on
EOF

# fstab
cat <<EOF > /etc/fstab
LABEL=ALPINE    /boot           vfat    defaults          0       2
LABEL=ROOT      /               ext4    defaults,noatime  0       1
EOF

cat <<EOF >> /etc/sysctl.conf
vm.vfs_cache_pressure=500
vm.swappiness=100
vm.dirty_background_ratio=1
vm.dirty_ratio=50
EOF

cat <<EOF > /etc/modules-load.d/i2c.conf
i2c-dev
EOF
