#!/usr/bin/env bash

set -xe

wget -q --show-progress --progress=bar:force:noscroll --continue \
  -P /tmp/ https://github.com/go-task/task/releases/download/v3.9.2/task_linux_amd64.tar.gz

tar -C /tmp/ -zvxf /tmp/task_linux_amd64.tar.gz task
/tmp/task -t Taskfile.yml
